### ISSUE TITLE
`common-config.yml` should not be required to be first element of `VarFiles`

### ISSUE THREAD

**Issue by yngvark** [oslokommune/ok#314]
... for schema config and migration to work.

# Description

If `package.yml` does this:

```yml
    - OutputFolder: app-common
      Template: app-common
      Ref: app-common-v3.1.3
      VarFiles:
        - _config/app-hello.yml
        - _config/common-config.yml
```

instead of this:

```yml
    - OutputFolder: app-common
      Template: app-common
      Ref: app-common-v3.1.3
      VarFiles:
        - _config/common-config.yml
        - _config/app-hello.yml
```

then `ok` thinks `common-config.yml` is an app config.

Relevant source code: https://github.com/oslokommune/ok/blob/706ee99a076e8c40358c787bed4ae54b67886962/pkg/pkg/update/update.go#L145

Figure out how to deal with this. We want to avoid relying on list order.

# Motivation

More robustness.f
