### ISSUE TITLE
Design and document new package file format specification

### ISSUE THREAD

**Issue by staticaland** [oslokommune/ok#418]
Design and document new package file format specification.

**Comment by staticaland** [comment]
## Docker compose-inspired

```yaml
version: "1"

include:                      # zero or more files, evaluated in order
  - ../common-config.yml      # may contain only `vars:` or a full template
  - ./boilerplate-base.yml    # company defaults

template:                     # exactly one template per file
  repo: git@github.com:oslokommune/golden-path-boilerplate.git
  path: boilerplate/terraform/app
  ref:  app-v9.10.2
  output_folder: "."
  non_interactive: true

vars:                         # inline values override everything inherited
  Title: "Boilerplate (dev)"
  ShowLogo: false
```
